### ISSUE TITLE
Optimize detection of new episodes

### ISSUE THREAD

**Issue by Eloston** [TheEnigmaBlade/holo#3]
Parsing the HTTP headers for the content length is better than downloading the entire feed data.

FUNimation includes `Content-Length` in the HTTP header for `http://www.funimation.com/feeds/ps/videos?ut=FunimationSubscriptionUser&show_id=SHOW_ID`. (You can send the `HEAD` command to get this)

Crunchyroll doesn't include `Content-Length` for some reason, but they do support partial GET requests (i.e. including `Range` in the `GET` request). Then `Content-Range` will be included in the response header, which includes the total length of the content (after compression I believe). I used the URL of the form `http://www.crunchyroll.com/SHOW_NAME.rss` for testing.

I haven't tested other URLs or sites, but hopefully they work similarly.

**Comment by TheEnigmaBlade** [comment]
Based on the results of some testing, HEAD requests (for Crunchyroll in particular) have negligible time cost improvements and would likely _increase_ run time due to the need to make an additional GET for information when a new episode is found.

The only improvement is lowering bandwidth usage, but that's not something I'm particularly worried about right now.
